# Generated by Django 3.2.25 on 2025-01-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.CharField(max_length=50, verbose_name='eMail')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='celular')),
                ('funcao', models.CharField(blank=True, max_length=30, null=True, verbose_name='Funcao')),
                ('nascimento', models.DateField(blank=True, null=True, verbose_name='Nascimento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'ordering': ['nome', 'funcao'],
            },
        ),
    ]
