# Generated by Django 3.2.25 on 2025-01-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0003_auto_20250127_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='source',
            field=models.CharField(default='sentiment', max_length=50),
        ),
    ]
