# Generated by Django 3.2.25 on 2025-02-08 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0005_predictionhistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='usuario_pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sentiment.pessoa'),
        ),
    ]
