# Generated by Django 3.2.25 on 2025-02-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0006_predictionhistory_usuario_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='permissao_sentiment',
            field=models.BooleanField(default=False, verbose_name='Acesso Sentiment GPT'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='permissao_sentiment_ml',
            field=models.BooleanField(default=False, verbose_name='Acesso Sentiment ML'),
        ),
    ]
