# Generated by Django 5.1.6 on 2025-02-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0008_auto_20250208_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionhistory',
            name='source',
            field=models.CharField(default='sentiment_gpt', max_length=50),
        ),
    ]
