# Generated by Django 5.1.6 on 2025-02-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0009_alter_predictionhistory_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='token',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
